name: Build
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
on:
  pull_request: {}
  push:
    branches:
      - main
env:
  SMOKE_PRODUCT_NAME: "kuma"
  SMOKE_PRODUCT_VERSION: "2.9.2"
  CI_TOOLS_DIR: "/home/runner/work/kuma-smoke/.ci_tools"
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: make dev/tools
        run: make dev/tools
      - name: make check
        run: make check
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m --verbose
          skip-cache: true
  build-test:
    name: Build and test
    needs:
      - check
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci/skip-test') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: make dev/tools
        run: |
          make dev/tools
          echo "${CI_TOOLS_DIR}/bin" >> $GITHUB_PATH
      - name: make build
        run: make build
      - name: make run
        run: make run
      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        if: always()
        with:
          name: smoke-report
          if-no-files-found: ignore
          path: |
            raw-report.json
            build/debug-output/*.log
          retention-days: ${{ github.event_name == 'pull_request' && 7 || 15 }}